Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using parcial2.Models;
using parcial2.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace parcial2.Controllers
{   
  // Solicita estar logueado para acceder
   [Authorize]
    public class StoreController : Controller
    {
        private readonly EnterpriseContext _context;

        public StoreController(EnterpriseContext context)
        {
            _context = context;
        }

        // GET: Store
        public async Task<IActionResult> Index()
        {
              return _context.Store != null ? 
                          View(await _context.Store.ToListAsync()) :
                          Problem("Entity set 'EnterpriseContext.Store'  is null.");
        }

        // GET: Store/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Store == null)
            {
                return NotFound();
            }

            var Store = await _context.Store
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Store == null)
            {
                return NotFound();
            }

            return View(Store);
        }

        // GET: Store/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Company")] StoreVM footwearStoreInput)
        {
            if (ModelState.IsValid)
            {
                var Store = new Store {
                    Name = footwearStoreInput.Name,
                    Company = footwearStoreInput.Company,
                };
                _context.Add(Store);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(footwearStoreInput);
        }

        // GET: Store/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Store == null)
            {
                return NotFound();
            }

            var Store = await _context.Store.FindAsync(id);
            if (Store == null)
            {
                return NotFound();
            }
            return View(Store);
        }

        // POST: Store/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Company")] Store Store)
        {
            if (id != Store.Id)
            {
                return NotFound();
            }

            
            {
                try
                {
                    _context.Update(Store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FootwearStoreExists(Store.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Store);
        }

        // GET: Store/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Store == null)
            {
                return NotFound();
            }

            var Store = await _context.Store
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Store == null)
            {
                return NotFound();
            }

            return View(Store);
        }

        // POST: Store/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Store == null)
            {
                return Problem("Entity set 'EnterpriseContext.Store'  is null.");
            }
            var Store = await _context.Store.FindAsync(id);
            if (Store != null)
            {
                _context.Store.Remove(Store);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FootwearStoreExists(int id)
        {
          return (_context.Store?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - parcial2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/parcial2.styles.css" asp-append-version="true" />
    <style>
        /* Agregamos estilos personalizados */
        .navbar-nav {
            width: 90%;
            display: flex;
            justify-content: center;
            margin-left: 10%;
        }

        .navbar-nav .nav-item {
            text-align: center;
            margin: 10px 20px; /* Ajusta los valores de margen según tus preferencias */
        }

        .nav-link-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .exclusive-text {
            font-size: 0.8em;
            color: #888;
        }

        /* Mueve _LoginPartial al margen superior derecho */
        .ml-auto {
            margin-left: auto !important;
        }
    </style>
</head>
<body style="background-color: #f8f9fa;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-items-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <div class="nav-link-container">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Footwear" asp-action="Product">Calzados</a>
                                
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="nav-link-container">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Footwear" asp-action="Index">Alta de Calzados</a>
                                <span class="exclusive-text">(Exclusivo para usuarios)</span>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="nav-link-container">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Alta de Tiendas</a>
                                <span class="exclusive-text">(Exclusivo para usuarios)</span>
                            </div>
                        </li>
                    </ul>
                    <div class="ml-auto"> <!-- Mueve _LoginPartial al margen superior derecho -->
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>